baseURL: "https://reinbugnot.github.io" 
title: Rein Bugnot
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: CV
          url: cv/
          weight: 1 
        - name: Projects
          url: projects/
          weight: 2
        - name: Blog
          url: blog/
          weight: 3

params:
    description: "I am a Professor of Philology at the Institute of Romance Philology in Regensburg, Germany. My research focuses mostly on Portuguese irregular verbs.
consequat."
    author: Rein Bugnot
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Rein Bugnot
          subtitle: "Test. This is a template for my self-introduction."
          imageUrl: "Casual Pic - Square.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Rein Bugnot
          buttons:
            - name: CV
              url: BUGNOT - RESUME v2.pdf
            - name: Projects
              url: projects/
            - name: Blog
              url: blog/

    socialIcons:
        - name: Email
          url: mailto:reinbugnot@gmail.com
        - name: Linkedin
          url: https://www.linkedin.com/in/reinbugnot/
        - name: GitHub
          url: https://github.com/reinbugnot

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Rein Bugnot"
      icon: rein-icon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2